<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CatLib</AssemblyName>
    <RootNamespace>CatLib</RootNamespace>
    <Version>0.5.0</Version>
    <PluginGuid>catlib.core</PluginGuid>
    <PluginMetaName>CatLib</PluginMetaName>
    <CatLibDeployFolder>CatLib</CatLibDeployFolder>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CatLib.Tests" />
  </ItemGroup>
</Project>
