<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CatLib</AssemblyName>
    <RootNamespace>CatLib</RootNamespace>
    <Version>0.7.0</Version>
    <PluginGuid>catlib.core</PluginGuid>
    <PluginMetaName>CatLib</PluginMetaName>
    <CatLibDeployFolder>CatLib</CatLibDeployFolder>
    <CatLibIcon>$(CatLibRoot)icon.png</CatLibIcon>
    <CatLibThunderstoreChangelog>$(CatLibRoot)CHANGELOG.md</CatLibThunderstoreChangelog>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CatLib.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\tools\CatLib.CrashWatcher\CatLib.CrashWatcher.csproj" ReferenceOutputAssembly="false" SkipGetTargetFrameworkProperties="true" Private="false" />
  </ItemGroup>
</Project>
